### ISSUE TITLE
בקשה: צביעת סכום שלילי באדום וחיובי בירוק

### ISSUE THREAD

**Issue by ariely87** [OfirYemini/collector-manager#10]
במקרה שפספסתי להקליד מינוס באחת העברות, יהיה לי הרבה יותר קל לאתר את זה אם הסכום  השלילי יהיה צבוע באדום והחיובי בירוק

**Comment by OfirYemini** [comment]
סבבה הוספתי
תלחץ ctrl+f5 לרענן את ה cache של ה browser
