### ISSUE TITLE
בקשה:  נוטיפיקציה לאחר לחיצה על '+' בדף של התבנית 

### ISSUE THREAD

**Issue by ariely87** [OfirYemini/collector-manager#12]
לאחר שאני מסיים להקליד תבנית אני לוחץ על + וזה מזין לי את הנתונים למאגר.
הבעיה היא שאין שום נוטיפיקציה על זה. 

אם אפשר:
1. שתהיה הודעה על כך שהפעולות הוזנו
2ניקוי אוטומטי של  כל השדות בטופס התבנית

**Comment by OfirYemini** [comment]
fixed, please test and close
