### ISSUE TITLE
תנועות נעלמות מהמאגר

### ISSUE THREAD

**Issue by ariely87** [OfirYemini/collector-manager#13]
יש תנועות שנעלמות ממאגר התנועות, לדעתי זה קרה כשניסיתי לערוך אותן
לדוגמא 
![image](https://user-images.githubusercontent.com/57153379/76864740-47e16f80-686a-11ea-828f-e806701b1fa9.png)

**Comment by OfirYemini** [comment]
ויזואלי בלבד, חיפוש לא בטווח ברירצ מחדל של תאריכים. שדה ברירת מחדל של תאריך מוצג עכשיו .
![image](https://user-images.githubusercontent.com/10131199/77236587-c1f65900-6bc8-11ea-8c95-045be4239133.png)
