### ISSUE TITLE
הוספת סוג תנועה 'אחר'

### ISSUE THREAD

**Issue by ariely87** [OfirYemini/collector-manager#2]
תחת 'סוג תנועה' צריכה להיות אפשרות כללית  למקרה שהתנועה לא מתאימה לאף אחד מהתנועות המוצעות.

**Comment by OfirYemini** [comment]
האם מספיק להושיף שדה זכות?

**Comment by OfirYemini** [comment]
הוספתי

![image](https://user-images.githubusercontent.com/10131199/72669057-f1a4ab80-3a35-11ea-91da-ba0aecce0f72.png)

**Comment by ariely87** [comment]
כדאי להוסיף שדה" אחר" עבור חיוב ולא זיכוי. אולי מתישהו ימכרו איזה משהו שלא מופיע ברשימה

**Comment by OfirYemini** [comment]
טוב

![image](https://user-images.githubusercontent.com/10131199/72669137-09306400-3a37-11ea-8de6-cdd659a3506a.png)
