### ISSUE TITLE
שדה 'סכום' צריך לקבל ערכים שליליים

### ISSUE THREAD

**Issue by ariely87** [OfirYemini/collector-manager#3]
במקרה שרוצים להזין למתפלל זיכוי , צריכה להיות אפשרות להכניס לסכום ערך שלילי

**Comment by OfirYemini** [comment]
אתה מתכוון לחיובי? כל הטרנזקציות צריכות להיות עם ערך שלילי חוץ מזיכוי

**Comment by OfirYemini** [comment]
![image](https://user-images.githubusercontent.com/10131199/72669061-0719d580-3a36-11ea-9f19-a34a2228bb08.png)

**Comment by ariely87** [comment]
מצויין, לזה התכוונתי

**Comment by OfirYemini** [comment]
יש אפשרות
![image](https://user-images.githubusercontent.com/10131199/72669065-27499480-3a36-11ea-8dfd-c8139d295c88.png)
