### ISSUE TITLE
בקשה: לאחר לחיצה על "הוספת תנועה" להעביר את הפוקוס על תחילת השורה הבאה

### ISSUE THREAD

**Issue by ariely87** [OfirYemini/collector-manager#6]
-אני עובד עם המקלדת ובכל פעם שאני לוחץ על כפתור הוספת תנועה 
![image](https://user-images.githubusercontent.com/57153379/75117796-727e4500-567d-11ea-94e2-b993332bfbf7.png)
אני צריך עם העכבר לעבור לשורה של תנועה חדשה. 

![image](https://user-images.githubusercontent.com/57153379/75117813-a8bbc480-567d-11ea-9994-90beaeb4f9df.png)

**Comment by OfirYemini** [comment]
fixed
