### ISSUE TITLE
בקשה: הוספת מתפלל בשם "אורחים"

### ISSUE THREAD

**Issue by ariely87** [OfirYemini/collector-manager#8]
במהלך הזנת נתונים כשאני צריך להזין אורח אני חייב לעבור ללשונית "מתפללים" ושם לעדכן את השם של האורח ולסמן אותו כאורח ורק אז לחזור להזנה . זה תהליך מסורבל ולא נוח.
אני מעדיף שיהיה יוזר אחד של אורחים שאליו נפנה את כל ההעברות של האורחים, ואת שם האורח נכתוב בהערה של התנועה

**Comment by OfirYemini** [comment]
זה יהיה בעייתי אחר כך בהוצאה של הדוחות, הדוח מתפלג לפי Id של מתפלל, אני לא יכול לאפשר לך לכתוב טקסט בהערה ולהסתמך על זה כ Id. מחר תטעה בשם וזה יתפלג כמתפלל שונה. לדעתי תפתח שני טאבים בדפדפן אחד ליד בשני, אחד על מתפללים ואחד על תנועות. גם ככה באיזה שהוא שלב זה יהיה נדיר להוסיף אורח חדשץ אם יש לך רעיון אחר שיקל עליך תגיד

**Comment by ariely87** [comment]
מאוד חשוב לי הרציפות של הכנסת התנועות, אני לא יכול לעצור את כל התהליך רק בשביל להוסיף אורח חדש יש שבתות או חגים שבהם יש כמה אנשים חדשים . מצד שני אני מבין למה אתה מתכוון.

יש לי הצעה , תגיד לי כמה זה מסובך:
במידה ומכניסים בשדה של המתפלל שם שלא קיים במאגר,  לאחר לחיצה על הכנסת תנועה, המערכת תזהה ותזרוק שאילתא בסגנון "מתפלל לא קיים, האם ליצור חדש?"
כשמתפלל יווצר בצורה הזאת הוא יסומן דיפולטיבית כאורח וייכנס למאגר.

**Comment by OfirYemini** [comment]
רעיון טוב, אני אבדוק אם זה לא מסובך מדי

**Comment by ariely87** [comment]
לא צריך את זה בסוף
