### ISSUE TITLE
בקשה: החלפת עמודת התאריך בדו"ח

### ISSUE THREAD

**Issue by ariely87** [OfirYemini/collector-manager#9]
התאריך שמופיע בדוחו"ת הוא התאריך של הזנת הפעולה, ולא התאריך של הקנייה. 
אני חושב שמה שיעניין את המתפלל הוא מתי הוא קנה ולא מתי עדכנתי את זה. 
![image](https://user-images.githubusercontent.com/57153379/76624522-23218b00-653e-11ea-8998-28cdd6dea416.png)

אני מציע להחליף את התוכן של עמודת "תאריך" בתוכן של "תיאור" הפעולה, ששם אני מקפיד לרשום מתי בוצעה הקנייה

**Comment by OfirYemini** [comment]
ממש לא, אתה אמור לבחור בהכנסת תנועה את התאריך שבו התבצעה הפעולה. כברירת מחדל יש לך את התאריך שבו הכנסת את התנועה. אבל אני רואה שיש לך בעיה אחרת כאן עם ה undefined

**Comment by ariely87** [comment]
אם אני קונה רביעי נניח, זה לא יעניין אותי לראות שקניתי אותו ב11.3 , וגם לא בכ"ח שבט. מה שיעניין אותי זה שזה היה בפרשת ויחי, מבין למה אני מתכוון? התנועות כולן מתבצעות בשבתות או חגים, והרבה יותר קל למתפללים להבין מתי בדיוק זה היה אם מדברים איתם עם השבת או החג.
בעמודת "תיאור" אני מציין אם זה היה בשבת או החג.
מבחינתי אפשר לחלוטין להעלים את התאריך מהמתפלל.

**Comment by ariely87** [comment]
הנה דוגמא לפורמט הישן, ככה היינו מציגים את הדוחות למתפללים עד היום:
![image](https://user-images.githubusercontent.com/57153379/77145754-16e38380-6a92-11ea-982f-a3796e866bdb.png)

**Comment by OfirYemini** [comment]
הבנתי, סבבה

**Comment by OfirYemini** [comment]
![image](https://user-images.githubusercontent.com/10131199/78461188-9b0f4b00-76cf-11ea-8c00-5fb044b8d977.png)

תוקן
